#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3

import wx
from oc_designGUI import oc_designGUI

class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frameMain = oc_designGUI(None, -1, "")
        self.SetTopWindow(frameMain)
        frameMain.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    App_ = MyApp(0)
    App_.MainLoop()
