# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wxcustom.oc_wxLogCtrl as oc_wxLogCtrl
# end wxGlade

class oc_designGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: oc_designGUI.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.splitterMain = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.windowMainDown = wx.Panel(self.splitterMain, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self.windowMainUp = wx.Panel(self.splitterMain, -1)
        self.splitterLog = wx.SplitterWindow(self.windowMainUp, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.windowLogDown = wx.Panel(self.splitterLog, -1)
        self.windowLogUp = wx.Panel(self.splitterLog, -1)
        
        # Menu Bar
        self.frameMain_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.frameMain_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.frameMain_menubar.Append(wxglade_tmp_menu, "item")
        self.SetMenuBar(self.frameMain_menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.toolbar)
        self.toolbar.AddLabelTool(10050, "Start", wx.Bitmap("images/control_play_blue.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.toolbar.AddLabelTool(10051, "Stop", wx.Bitmap("images/control_stop_blue.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.toolbar.AddSeparator()
        self.toolbar.AddLabelTool(10052, "AutoScroll", wx.Bitmap("images/arrow_down.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_CHECK, "", "")
        # Tool Bar end
        self.logCtrl = oc_wxLogCtrl.LogCtrl(self.windowLogUp, -1)
        self.txtCtrlLogInfo = wx.TextCtrl(self.windowLogDown, -1, "", style=wx.NO_BORDER)
        self.txtctrlLogApp = wx.TextCtrl(self.windowMainDown, -1, "", style=wx.TE_MULTILINE|wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.onAutoScroll, id=10052)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: oc_designGUI.__set_properties
        self.SetTitle("OctopyLog")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\CVS_Local\\octopylog\\src\\images\\octopussy.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.toolbar.SetToolBitmapSize((16, 16))
        self.toolbar.SetMargins((2, 2))
        self.toolbar.SetToolPacking(2)
        self.toolbar.SetToolSeparation(2)
        self.toolbar.Realize()
        self.logCtrl.SetMinSize((673,250))
        self.txtCtrlLogInfo.SetMinSize((675, 134))
        self.txtctrlLogApp.SetMinSize((684, 125))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: oc_designGUI.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.logCtrl, 1, wx.EXPAND, 0)
        self.windowLogUp.SetSizer(sizer_4)
        sizer_5.Add(self.txtCtrlLogInfo, 1, wx.EXPAND, 0)
        self.windowLogDown.SetSizer(sizer_5)
        self.splitterLog.SplitHorizontally(self.windowLogUp, self.windowLogDown)
        sizer_3.Add(self.splitterLog, 1, wx.EXPAND, 0)
        self.windowMainUp.SetSizer(sizer_3)
        sizer_2.Add(self.txtctrlLogApp, 1, wx.EXPAND, 0)
        self.windowMainDown.SetSizer(sizer_2)
        self.splitterMain.SplitHorizontally(self.windowMainUp, self.windowMainDown)
        sizer_1.Add(self.splitterMain, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onAutoScroll(self, event): # wxGlade: oc_designGUI.<event_handler>
        print "Event handler `onAutoScroll' not implemented!"
        event.Skip()

# end of class oc_designGUI


